#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
# Copyright (c) 2012, NVIDIA CORPORATION.  All rights reserved.
#
# SPDX-License-Identifier:	GPL-2.0+
#


obj-y				+= rtonboot.o
obj-y				+= asm.o
obj-y				+= mmu.o
obj-y				+= platform.o



