#!/bin/sh
#
# Start the rteth network....
#

start() {
    echo "Setting up network forwarding between eth0 and rteth0..."
    
	iptables -F
	iptables -t nat -F
	iptables -X
	iptables -t nat -X
	
	iptables -P INPUT ACCEPT
	iptables -P FORWARD ACCEPT
	iptables -P OUTPUT ACCEPT
	iptables -t nat -P PREROUTING ACCEPT
	iptables -t nat -P POSTROUTING ACCEPT
	
	# iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
	
	iptables -A FORWARD -i eth0 -o rteth0 -m state --state RELATED,ESTABLISHED -j ACCEPT

	iptables -A FORWARD -i rteth0 -o eth0 -j ACCEPT

	iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

    echo 1 > /proc/sys/net/ipv4/ip_forward
    
    ifconfig eth0 192.168.1.188 netmask 255.255.255.0 up
    
    route add -net 192.168.1.1 netmask 255.255.255.0 dev eth0
    
    ifconfig rteth0 192.168.2.1 netmask 255.255.255.0 up
        
    echo "Network forwarding setup complete."
}

stop() {
    echo "Clearing network forwarding rules..."
    echo 0 > /proc/sys/net/ipv4/ip_forward
    echo "Network forwarding rules cleared."
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
