#ifndef _ERROR_NUM_H_
#define _ERROR_NUM_H_

#define ERROR_NUM_OK 0
#define ERROR_NUM_SIGNAL_FAIL -1
#define ERROR_NUM_OPEN_BRIDGE_FAIL -2
#define ERROR_NUM_GET_BUF_PARA_FAIL -3
#define ERROR_NUM_BRIDGE_MMAP_FAIL -4
#define ERROR_NUM_CREATE_MSG_IOCTL_FAIL -5
#define ERROR_NUM_CREATE_MSG_TIMEOUT_FAIL -6
#define ERROR_NUM_CREATE_MSG_SEMWAIT_FAIL -7
#define ERROR_NUM_CREATE_MSG_REP_STATUS_FAIL -8
#define ERROR_NUM_CREATE_MSG_MALLOC_ITEM_FAIL -9
#define ERROR_NUM_LIST_EMPTY_SEND_FAIL -10
#define ERROR_NUM_NOT_FOUND_SEND_FAIL -11
#define ERROR_NUM_IOCTL_SEND_FAIL -12
#define ERROR_NUM_LIST_EMPTY_CALL_END_FAIL -13
#define ERROR_NUM_NOT_FOUND_CALL_END_FAIL -14
#define ERROR_NUM_LIST_EMPTY_CALL_RESP_FAIL -15
#define ERROR_NUM_NOT_FOUND_CALL_RESP_FAIL -16
#define ERROR_NUM_RR_RESP_IOCTL_FAIL -17
#define ERROR_NUM_OPEN_BULK_FAIL -18
#define ERROR_NUM_GET_BULK_PARA_FAIL -19
#define ERROR_NUM_BULK_MMAP_FAIL -20
#define ERROR_NUM_BULK_NOT_INITED_FAIL -21
#define ERROR_NUM_BULK_CREATE_MSGS_FAIL -22
#define ERROR_NUM_RECEIVE_BROADCAST_IOCTL_FAIL -23
#define ERROR_NUM_UN_RECEIVE_BROADCAST_IOCTL_FAIL -24
#define ERROR_NUM_GET_NET_PORT_IDX_IOCTL_FAIL -25
#define ERROR_NUM_INVALID_NET_PORT_IDX_FAIL -26
#define ERROR_NUM_CREATE_MSG_READ_FAIL -27
#define ERROR_NUM_SET_TRACE_LEVEL_FAIL -28
#define ERROR_NUM_USER_TRACE_IOCTL_FAIL -29
#define ERROR_NUM_SANERFA_IOCTL_FAIL -30
#define ERROR_CPYBUF_IOCTL_FAIL -31
#define ERROR_CREATE_READMSG_THREAD_FAIL -46

#endif
