#ifndef _MSGID_H_
#define _MSGID_H_

#ifdef __cplusplus 
extern "C" {
#endif


#ifdef INCLUDE_NONPUB

#define MSGID_CREATE_MSG 0
#define MSGID_DESTORY_MSG 1
#define MSGID_RECEIVE_BROADCAST_MSG 2

#define MSGID_USER_BEGIN 3

#define MSGID_EXECCMD_ON_RTOS (MSGID_USER_BEGIN + 1)
#define MSGID_SEND_EXECCMD_RESULT (MSGID_USER_BEGIN + 2)
#define MSGID_TESTRR (MSGID_USER_BEGIN + 3)
#define MSGID_TESTBC (MSGID_USER_BEGIN + 4)
#define MSGID_TESTBC_DUMMY (MSGID_USER_BEGIN + 5)

#endif

#define MSGID_RTPUB_USER_BEGIN 9

#define MSGID_TESTK3 MSGID_RTPUB_USER_BEGIN
#define MSGID_LINUX_BULK_READY_MSG (MSGID_RTPUB_USER_BEGIN + 1)
#define MSGID_RTOS_BULK_READY_MSG (MSGID_RTPUB_USER_BEGIN + 2)

#define MSGID_START_EC (MSGID_RTPUB_USER_BEGIN + 3)
#define MSGID_CLEANUP_AFTER_EC (MSGID_RTPUB_USER_BEGIN + 4)

#define MSGID_EC_MASTER_READY (MSGID_RTPUB_USER_BEGIN + 5)
#define MSGID_START_EC_CYCLIC (MSGID_RTPUB_USER_BEGIN + 6)
#define MSGID_STOP_EC_CYCLIC (MSGID_RTPUB_USER_BEGIN + 7)

#define MSGID_EC_INTER_GET_MASTER_READY (MSGID_RTPUB_USER_BEGIN + 8)
#define MSGID_START_EC_INTER (MSGID_RTPUB_USER_BEGIN + 9)
#define MSGID_STOP_EC_INTER (MSGID_RTPUB_USER_BEGIN + 10)

#define MSGID_FOE_WRITE (MSGID_RTPUB_USER_BEGIN + 11)
#define MSGID_FOE_READ (MSGID_RTPUB_USER_BEGIN + 12)

#define MSGID_EC_CYCLIC_PERF (MSGID_RTPUB_USER_BEGIN + 13)

#define MSGID_TEST_SLAVE (MSGID_RTPUB_USER_BEGIN + 14)

#define MSGID_START_SIMPLETEST (MSGID_RTPUB_USER_BEGIN + 15)
#define MSGID_STOP_SIMPLETEST (MSGID_RTPUB_USER_BEGIN + 16)

#define MSGID_START_MOTORCTL (MSGID_RTPUB_USER_BEGIN + 17)
#define MSGID_STOP_MOTORCTL (MSGID_RTPUB_USER_BEGIN + 18)

#define MSGID_START_MOTORPP (MSGID_RTPUB_USER_BEGIN + 19)
#define MSGID_STOP_MOTORPP (MSGID_RTPUB_USER_BEGIN + 20)
#define MSGID_MOTORPP_UPDATE_POS (MSGID_RTPUB_USER_BEGIN + 21)

#define MSGID_SII_WRITE (MSGID_RTPUB_USER_BEGIN + 22)

#define MSGID_RTETH_SEND (MSGID_RTPUB_USER_BEGIN + 23)
#define MSGID_RTETH_RECV (MSGID_RTPUB_USER_BEGIN + 24)

#define SINGLE_RTETH_BUFFER_SIZE 1500

#define MSG_ORIGIN_LINUX 0
#define MSG_ORIGIN_RTOS 1

#define MSG_HAS_RESPONSE 0
#define MSG_NO_RESPONSE 1

#define RESP_STATUS_SUCCESS 0
#define RESP_STATUS_NOMEM 1
#define RESP_STATUS_MSG_DUPLICATE 2
#define RESP_STATUS_NO_FOUND 3

#define PID_BROADCAST_MSG 0xffffffff
#define PID_KERNEL_MSG 0xfffffffe

#ifdef __cplusplus 
}
#endif 

#endif
