/* version.h -- Autogenerated! Do not edit. */

#ifndef __INCLUDE_NUTTX_VERSION_H
#define __INCLUDE_NUTTX_VERSION_H

#define CONFIG_VERSION_STRING "12.4.0"
#define CONFIG_VERSION_MAJOR 12
#define CONFIG_VERSION_MINOR 4
#define CONFIG_VERSION_PATCH 0
#define CONFIG_VERSION_BUILD "96c2707737"

#define CONFIG_VERSION ((CONFIG_VERSION_MAJOR << 16) |\
                        (CONFIG_VERSION_MINOR << 8) |\
                        (CONFIG_VERSION_PATCH))

#endif /* __INCLUDE_NUTTX_VERSION_H */
